services:
  nginx:
    image: ghcr.io/1nbuc/instant-proxy:11
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./certs:/etc/nginx/certs
    environment:
      SSL_PORTS: 443
      PORTS: 80
      CONTAINER_ADDR: hardware-inventory:3000
